import { readFileSync, writeFileSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const rootDir = resolve(__dirname, '..');

const katexDistDir = resolve(rootDir, 'node_modules/katex/dist');
const cssPath = resolve(katexDistDir, 'katex.min.css');
const fontsDir = resolve(katexDistDir, 'fonts');
const outputPath = resolve(rootDir, 'src/generated/katexEmbeddedCss.ts');

const css = readFileSync(cssPath, 'utf-8');

// Replace each woff2 font URL with base64 data URI
let embeddedCss = css.replace(
  /url\(fonts\/(KaTeX_[^)]+\.woff2)\)/g,
  (_, fontFile: string) => {
    const fontPath = resolve(fontsDir, fontFile);
    const fontData = readFileSync(fontPath);
    const base64 = fontData.toString('base64');
    return `url(data:font/woff2;base64,${base64})`;
  }
);

// Remove woff and ttf fallbacks from @font-face
// Pattern: ,url(fonts/...woff) format("woff"),url(fonts/...ttf) format("truetype")
embeddedCss = embeddedCss.replace(
  /,url\(fonts\/[^)]+\.woff\) format\("woff"\),url\(fonts\/[^)]+\.ttf\) format\("truetype"\)/g,
  ''
);

const output = `// Auto-generated by scripts/generateKatexEmbeddedCss.ts
// Do not edit manually

export const katexEmbeddedCss = \`${embeddedCss.replace(/`/g, '\\`').replace(/\$/g, '\\$')}\`;
`;

writeFileSync(outputPath, output);

console.log('Generated katexEmbeddedCss.ts');
